encoding: utf-8

plugins:
  - jekyll-regex-replace

# SEO相关信息
title: Roy Blog
description: Roy的个人博客
keywords: Roy,Blog,Net Core, Vue, 数据库, 中间件, 缓存, 消息队列, 运维相关技术
author: Roy
footerText: 'Copyright © 2025 wangyongan.com. All Rights Reserved.'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://blog.wangyongan.com'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/769864

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 评论系统 Giscus
# 请在 https://giscus.app/ 获取你的配置
extGiscus: true
giscus:
  repo: '' # 你的仓库 owner/repo(data-repo)
  repoId: '' # 你的仓库 ID(data-repo-id)
  category: '' # 你的分类名称(data-category)
  categoryId: '' # 你的分类 ID(data-category-id)

# 友情链接
links:
  - title: blog wang
    url: https://blog.csdn.net/hello_mr_anan?type=blog
